### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by Toshibass** [tzapu/WebSocketSerialMonitor#2]
Hi Tzapu I have installed websocket serial monitor on a wemos mini and it appears to work as designed, whilst I still have it connected to com4 I see on the serial monitor ....

*WM: 
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 3
*WM: IP Address:
*WM: 192.168.0.52
START MIRRORING SERIAL
192.168.0.52
922 scaled_sensorValue 0: 0
999 scaled_sensorValue 1: 100
994 scaled_sensorValue 2: 100
1008 scaled_sensorValue 3: 100

However when I try pointing my web browser at  http://192.168.0.52:81/ all I see is ....

This is a Websocket server only!

Any idea what goes wrong ?

**Comment by tzapu** [comment]
hi, the files are not on the actual esp, use this page to connect:
http://tzapu.github.io/WebSocketSerialMonitor/
and connec to your ip

didn t develop this further as it seems there s not much interest

good luck

**Comment by Toshibass** [comment]
Oh right, I must learn to **read instructions properly**, now it works perfectly, I can only assume that as you say "not much interest" is due to no one finding this really cool program its brilliant, to put it into context I am currently building a greenhouse monitor so I have a wemos mini with OTA, 3 soil sensors and a light sensor, dht22 and some ds18b20 temp sensors .. this will all connect back to node-red via mqtt to control solenoid valves to auto water my tomatoes with indication and overide provided by node-red-contrib-blynk-websockets, being able to monitor the serial output remotely will make it so easy to tweak and modify my code and see the results in real time, Having only just got OTA working, my next mission will be to convert all my other project over to ota and I will be able to use this proxy serial monitor on any of those just by connecting two wires  S U P E R B 

Just one final question ... how to locate "download (from gh-pages branch)" for the serial monitor

Thanks for you time and effort to build this and other software I am a big fan cheers

**Comment by tzapu** [comment]
thank you very very much for you kind words.
just as a word of warning, for me, at times, it seems to miss some parts of the serial output. have not gotten to the bottom of it yet. it works good enough to see whatever i need though.

download the page from here
https://github.com/tzapu/WebSocketSerialMonitor/tree/gh-pages 

i think a d1 mini has a low drop voltage reg, my plan was to have a permanent battery powered debugger :)

when you are done with the project, let me know if you share it somewhere, i ve got a couple of friends that want to build similar things for themselves. it sounds really cool (not for tomatoes, but hot peppers :P )

**Comment by Toshibass** [comment]
Further to the above I am finding this websocket serialMonitor really useful however I am trying to modify the webpage to include a Disconnect button next to the Connect button so that I can stop the information flow and scroll up to check previous events that have gone by .. so I added ....
    input type="button" value="Connect" onclick="connect(host.value)" /
    **input type="button" value="Disconnect" onclick="disconnect()" /**
(with the necessary arrows that don't show up on this post)
and a function...
    **function disconnect() {
    isRunning = false;
    connectionLabel.value = "Disconnected";
        socket.removeAllListeners();
        socket = null;
    }**

But it doesn't stop the connection or flow .. any chance you could help me out here.

**Comment by Toshibass** [comment]
OK sorted I guess I was trying to over think this ....
    function disconnect() {
    isRunning = false;
    connectionLabel.value = "Disconnected";
        socket.onclose = function () {};
        socket.close()
    }

**Comment by tzapu** [comment]
generally i ve had issues with not removing all event listeners, don t know if this is the case, but in case you are getting a double connection (or esp crash) when reconnecting after a disconnect, you might want to keep 
socket.removeAllListeners();
after socket.close()

cheers

**Comment by Toshibass** [comment]
Thanks for your response, however if I include   socket.removeAllListeners();  I get .. 
**Uncaught TypeError: socket.removeAllListeners is not a function**
thats why I didn't include it, in reality I am not seeing double connection or esp crash at the moment. 

also the  **function send(data){**  does not appear to do anything .. is it correct ?

**Comment by tzapu** [comment]
sorry, my bad, looked again and it does seem that close() should be enough

that s all i found in my code anyway
cheers
