### ISSUE TITLE
without proxy?

### ISSUE THREAD

**Issue by betyar** [tzapu/WebSocketSerialMonitor#5]
Is there anyway to do this without a proxy? What I would like is to somehow have the serial messages from an ESP8266 sent directly by WiFi via a websocket to a HTML textarea element. All I need is to see the serial messages for debugging purposes, no need to interact with the esp.

**Comment by tzapu** [comment]
the prompt to develop/use this was to see what's happening when you had no wifi connection

maybe this can help https://www.hackster.io/JoaoLopesF/still-debugging-your-wifi-projects-only-by-serial-print-bbce87
