### ISSUE TITLE
cannot bind non-const lvalue reference of type 'String&' to an rvalue of type 'String'

### ISSUE THREAD

**Issue by svdrummer** [tzapu/WebSocketSerialMonitor#6]
webSocket.sendTXT(num, "Connected to Serial on " + WiFi.localIP().toString() + "\n");
causes
exit status 1
cannot bind non-const lvalue reference of type 'String&' to an rvalue of type 'String'

**Comment by tzapu** [comment]
hey, really sorry about this but i have not touched this project and esps in a few years, i have no idea what's going on anymore

**Comment by shoei600** [comment]
This library seems perfect for my needs - thank you. But did anybody resolve this please? More details in the error below:

/Documents/Arduino/WebSocketSerialMonitor-master/WebSocketSerialMonitor/WebSocketSerialMonitor.ino: In function 'void webSocketEvent(uint8_t, WStype_t, uint8_t*, size_t)':
/Documents/Arduino/WebSocketSerialMonitor-master/WebSocketSerialMonitor/WebSocketSerialMonitor.ino:32:86: error: cannot bind non-const lvalue reference of type 'String&' to an rvalue of type 'String'
   32 |         webSocket.sendTXT(num, "Connected to Serial on " + WiFi.localIP().toString() + "\n");
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
In file included from /Documents/Arduino/WebSocketSerialMonitor-master/WebSocketSerialMonitor/WebSocketSerialMonitor.ino:11:
/Documents/Arduino/libraries/WebSockets/src/WebSocketsServer.h:60:40: note:   initializing argument 2 of 'bool WebSocketsServerCore::sendTXT(uint8_t, String&)'
   60 |     bool sendTXT(uint8_t num, String & payload);

**Comment by shoei600** [comment]
The code compiles when commenting out line 32:  
webSocket.sendTXT(num, "Connected to Serial on " + WiFi.localIP().toString() + "\n");
